/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReclamoRouteImport } from './routes/reclamo'
import { Route as RealizarPagoRouteImport } from './routes/realizar-pago'
import { Route as LugaresPagoRouteImport } from './routes/lugares-pago'
import { Route as IncidenciasRouteImport } from './routes/incidencias'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as IndexRouteImport } from './routes/index'

const ReclamoRoute = ReclamoRouteImport.update({
  id: '/reclamo',
  path: '/reclamo',
  getParentRoute: () => rootRouteImport,
} as any)
const RealizarPagoRoute = RealizarPagoRouteImport.update({
  id: '/realizar-pago',
  path: '/realizar-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const LugaresPagoRoute = LugaresPagoRouteImport.update({
  id: '/lugares-pago',
  path: '/lugares-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidenciasRoute = IncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/incidencias': typeof IncidenciasRoute
  '/lugares-pago': typeof LugaresPagoRoute
  '/realizar-pago': typeof RealizarPagoRoute
  '/reclamo': typeof ReclamoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/incidencias': typeof IncidenciasRoute
  '/lugares-pago': typeof LugaresPagoRoute
  '/realizar-pago': typeof RealizarPagoRoute
  '/reclamo': typeof ReclamoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/incidencias': typeof IncidenciasRoute
  '/lugares-pago': typeof LugaresPagoRoute
  '/realizar-pago': typeof RealizarPagoRoute
  '/reclamo': typeof ReclamoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historial'
    | '/incidencias'
    | '/lugares-pago'
    | '/realizar-pago'
    | '/reclamo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historial'
    | '/incidencias'
    | '/lugares-pago'
    | '/realizar-pago'
    | '/reclamo'
  id:
    | '__root__'
    | '/'
    | '/historial'
    | '/incidencias'
    | '/lugares-pago'
    | '/realizar-pago'
    | '/reclamo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorialRoute: typeof HistorialRoute
  IncidenciasRoute: typeof IncidenciasRoute
  LugaresPagoRoute: typeof LugaresPagoRoute
  RealizarPagoRoute: typeof RealizarPagoRoute
  ReclamoRoute: typeof ReclamoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reclamo': {
      id: '/reclamo'
      path: '/reclamo'
      fullPath: '/reclamo'
      preLoaderRoute: typeof ReclamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realizar-pago': {
      id: '/realizar-pago'
      path: '/realizar-pago'
      fullPath: '/realizar-pago'
      preLoaderRoute: typeof RealizarPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugares-pago': {
      id: '/lugares-pago'
      path: '/lugares-pago'
      fullPath: '/lugares-pago'
      preLoaderRoute: typeof LugaresPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidencias': {
      id: '/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof IncidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorialRoute: HistorialRoute,
  IncidenciasRoute: IncidenciasRoute,
  LugaresPagoRoute: LugaresPagoRoute,
  RealizarPagoRoute: RealizarPagoRoute,
  ReclamoRoute: ReclamoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
